---
- name: Configure and Deploy Node.js Application (No Handlers)
  hosts: app
  become: true

  vars:
    node_major_version: "18"
    app_path: "/home/ubuntu/node-app"

  tasks:
    # ... all the tasks for apt, NodeSource, etc. remain the same ...
    # (Update APT, install curl, create keyring dir, get GPG key, add repo, install nodejs)

    # THIS ENTIRE BLOCK OF TASKS IS MISSING FROM YOUR LATEST PIPELINE RUN
  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install prerequisite packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Ensure /etc/apt/keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add NodeSource GPG key
      ansible.builtin.get_url:
        url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
        dest: /etc/apt/keyrings/nodesource.gpg
        mode: '0644'

    - name: Add NodeSource repository for Node.js
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x nodistro main"
        state: present
        update_cache: yes

    - name: Install Node.js from NodeSource
      ansible.builtin.apt:
        name: nodejs
        state: present
# THE MISSING BLOCK ENDS HERE

    - name: Copy application files to the server
      ansible.builtin.synchronize:
        src: ../
        dest: "{{ app_path }}"
        recursive: yes
        delete: yes
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=ansible"
          - "--exclude=node_modules"
      # The 'notify' line is removed

    - name: Install application dependencies
      ansible.builtin.npm:
        path: "{{ app_path }}"
      become_user: ubuntu

    - name: Copy systemd service file
      ansible.builtin.copy:
        src: node-app.service
        dest: /etc/systemd/system/node-app.service
        owner: root
        group: root
        mode: '0644'
      # The 'notify' line is removed

    # THIS TASK IS THE KEY CHANGE
    - name: Ensure service is enabled and restarted on every deploy
      ansible.builtin.systemd:
        name: node-app
        enabled: yes
        state: restarted  # <-- This forces a restart on every run
        daemon_reload: yes # <-- Moved from the handler to here

# The 'handlers:' block is completely removed from the end of the file.
