---
- name: Deploy Node.js App
  hosts: app
  become: true
  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Ensure dependencies for NodeSource are installed
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Download NodeSource setup script for Node.js 20.x
      ansible.builtin.get_url:
        url: https://deb.nodesource.com/setup_20.x
        dest: /tmp/nodesource_setup.sh
        mode: '0755'

    # --- THIS TASK IS NOW CORRECTED ---
    - name: Execute NodeSource setup script to add repository
      ansible.builtin.shell:
        cmd: /tmp/nodesource_setup.sh
        # 'creates' is a direct parameter of the shell module.
        # It should not be nested under 'args:'.
        creates: /etc/apt/sources.list.d/nodesource.list
    # --- END OF CORRECTION ---

    - name: Install Node.js and npm from NodeSource repository
      ansible.builtin.apt:
        name: nodejs
        state: present

    - name: Install PM2 process manager globally
      community.general.npm:
        name: pm2
        global: yes
        state: present

    - name: Copy application files to the server
      ansible.builtin.synchronize:
        src: ../
        dest: /home/ubuntu/node-app/
        recursive: yes
        delete: yes
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=ansible"

    - name: Install application dependencies with npm
      community.general.npm:
        path: /home/ubuntu/node-app/

    - name: Ensure the application is started and managed by PM2
      ansible.builtin.shell:
        cmd: pm2 startOrRestart index.js --name node-app
      args:
        chdir: /home/ubuntu/node-app/
