---
- name: Deploy Simple Node.js App
  hosts: app
  become: true

  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Ensure dependencies for NodeSource are installed
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Download NodeSource setup script for Node.js 20.x
      ansible.builtin.get_url:
        url: https://deb.nodesource.com/setup_20.x
        dest: /tmp/nodesource_setup.sh
        mode: "0755"

    - name: Execute NodeSource setup script
      ansible.builtin.shell: /tmp/nodesource_setup.sh
      args:
        creates: /etc/apt/sources.list.d/nodesource.list

    - name: Install Node.js from NodeSource
      ansible.builtin.apt:
        name: nodejs
        state: present

    - name: Copy application files to the server
      ansible.builtin.synchronize:
        src: ../
        dest: /home/ubuntu/node-app/
        recursive: yes
        delete: yes
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=ansible"
          - "--exclude=node_modules"

    - name: Install application dependencies
      ansible.builtin.shell: npm install
      args:
        chdir: /home/ubuntu/node-app/

    - name: Stop any running Node.js process
      ansible.builtin.shell: |
        pkill -f "node index.js" || true

    - name: Start the application using nohup
      ansible.builtin.shell: |
        nohup node index.js > app.log 2>&1 &
      args:
        chdir: /home/ubuntu/node-app/
