---
- name: Configure and Deploy Node.js Application
  hosts: app
  become: true

  vars:
    # Set to the Node.js version used in your Jenkins/dev environment
    node_major_version: "18"
    # The path where your application will be deployed
    app_path: "/home/ubuntu/node-app"

  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install prerequisite packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gpg
        state: present

    - name: Ensure /etc/apt/keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add the NodeSource GPG key
      ansible.builtin.get_url:
        url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
        dest: /etc/apt/keyrings/nodesource.gpg
        mode: '0644'

    # This task directly creates the correct repository file, solving the GPG error
    - name: Create NodeSource repository file with "nodistro"
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/nodesource.list
        content: "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ node_major_version }}.x nodistro main"
        owner: root
        group: root
        mode: '0644'
      notify: Update apt cache # Notify the handler to run apt-get update

    - name: Install Node.js from NodeSource
      ansible.builtin.apt:
        name: nodejs
        state: present

    - name: Copy application source code to the server
      ansible.builtin.synchronize:
        src: ../
        dest: "{{ app_path }}"
        recursive: yes
        delete: yes
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=ansible"
          - "--exclude=node_modules"
      notify: Restart node app

    - name: Install application dependencies with npm
      ansible.builtin.npm:
        path: "{{ app_path }}"
      become_user: ubuntu

    - name: Copy the systemd service file for the app
      ansible.builtin.copy:
        src: node-app.service # This file should be in your 'ansible' directory
        dest: /etc/systemd/system/node-app.service
        mode: '0644'
      notify: Restart node app

    - name: Ensure the node app service is started and enabled on boot
      ansible.builtin.systemd:
        name: node-app
        enabled: yes
        state: started

  # Handlers are tasks that only run when notified by a change
  handlers:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Restart node app
      ansible.builtin.systemd:
        name: node-app
        state: restarted
        daemon_reload: yes
