---
- name: Deploy Simple Node.js App
  hosts: app
  become: true
  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Ensure dependencies for NodeSource are installed
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Download NodeSource setup script for Node.js 20.x
      ansible.builtin.get_url:
        url: https://deb.nodesource.com/setup_20.x
        dest: /tmp/nodesource_setup.sh
        mode: '0755'

    - name: Execute NodeSource setup script
      ansible.builtin.shell:
        cmd: /tmp/nodesource_setup.sh
        creates: /etc/apt/sources.list.d/nodesource.list

    - name: Install Node.js from NodeSource repository
      ansible.builtin.apt:
        name: nodejs
        state: present

    - name: Copy application files to the server
      ansible.builtin.synchronize:
        src: ../
        dest: /home/ubuntu/node-app/
        recursive: yes
        delete: yes
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=ansible"

    - name: Install application dependencies
      ansible.builtin.npm:
        path: /home/ubuntu/node-app/

    - name: Stop any existing application process
      ansible.builtin.shell:
        # This command finds any process with 'node index.js' and stops it.
        # '|| true' ensures this step doesn't fail if the app isn't running.
        cmd: "pkill -f 'node index.js' || true"

    - name: Start the application in the background
      ansible.builtin.shell:
        # 'nohup' keeps the app running after we disconnect.
        # '&' runs the command in the background.
        # Logs will be saved to app.log in the app directory.
        cmd: "nohup node index.js > app.log 2>&1 &"
      args:
        chdir: /home/ubuntu/node-app/
