---
- name: Deploy Simple Node.js App
  hosts: all
  become: yes

  vars:
    app_dir: /home/ubuntu/simple-app

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Node.js and npm
      apt:
        name:
          - nodejs
          - npm
        state: present

    - name: Remove old app directory if exists
      file:
        path: "{{ app_dir }}"
        state: absent

    - name: Recreate app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy Node.js app files
      copy:
        src: "{{ playbook_dir }}/../"
        dest: "{{ app_dir }}/"
        owner: ubuntu
        group: ubuntu
        mode: preserve

    - name: Install npm dependencies
      npm:
        path: "{{ app_dir }}"
        production: yes

    - name: Start the Node.js app with nohup
      shell: |
        nohup node index.js > app.log 2>&1 &
      args:
        chdir: "{{ app_dir }}"
      async: 0
      poll: 0
      become_user: ubuntu

    # Optional: Replace above with pm2 if needed in production
    # - name: Install pm2 globally
    #   npm:
    #     name: pm2
    #     global: yes

    # - name: Start app using pm2
    #   shell: |
    #     pm2 start index.js --name my-app
    #     pm2 save
    #   args:
    #     chdir: "{{ app_dir }}"
    #   become_user: ubuntu
