---
- name: Deploy Simple Node.js App with NodeSource and systemd
  hosts: app
  become: true
  vars:
    # Define the version of Node.js you want to install
    # See available versions at: https://github.com/nodesource/distributions
    node_major_version: "18"

  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install dependencies for adding new repositories
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present

    # ---- START: New tasks to install Node.js from NodeSource ----
    - name: Get NodeSource GPG key
      ansible.builtin.get_url:
        url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
        dest: /etc/apt/keyrings/nodesource.gpg
        mode: '0644'

    - name: Add NodeSource repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ node_major_version }}.x nodistro main"
        state: present
        update_cache: yes # Important: update cache after adding repo

    - name: Install Node.js from NodeSource
      ansible.builtin.apt:
        name: nodejs
        state: present
    # ---- END: New tasks ----

    - name: Copy application files to the server
      ansible.builtin.synchronize:
        src: ../
        dest: /home/ubuntu/node-app/
        recursive: yes
        delete: yes
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=ansible"
          - "--exclude=node_modules"

    - name: Install application dependencies
      ansible.builtin.npm:
        path: /home/ubuntu/node-app/
      become_user: ubuntu # Best practice: run as non-root user

    # ---- Using systemd for robust process management ----
    - name: Copy systemd service file
      ansible.builtin.copy:
        src: node-app.service # Assumes you created this file locally
        dest: /etc/systemd/system/node-app.service
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd and restart the application
      ansible.builtin.systemd:
        name: node-app
        daemon_reload: yes
        state: restarted
        enabled: yes # Make sure it starts on server boot
