---
- name: Deploy Simple Node.js App Without NodeSource or PM2
  hosts: app
  become: true

  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Node.js and npm from default Ubuntu repos
      ansible.builtin.apt:
        name:
          - nodejs
          - npm
        state: present

    - name: Copy application files to the server
      ansible.builtin.synchronize:
        src: ../
        dest: /home/ubuntu/node-app/
        recursive: yes
        delete: yes
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=ansible"
          - "--exclude=node_modules"

    - name: Install application dependencies
      ansible.builtin.shell:
        cmd: npm install
        chdir: /home/ubuntu/node-app/

    - name: Stop any running Node.js process
      ansible.builtin.shell:
        cmd: pkill -f "node index.js" || true

    - name: Start the application using nohup
      ansible.builtin.shell:
        cmd: nohup node index.js > app.log 2>&1 &
        chdir: /home/ubuntu/node-app/
