---
- name: Simple Node.js App Setup
  hosts: app
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Node.js (from Ubuntu repo)
      apt:
        name: nodejs
        state: present

    - name: Install npm
      apt:
        name: npm
        state: present

    - name: Create app directory
      file:
        path: /home/ubuntu/simple-app
        state: directory
        owner: ubuntu

    - name: Copy app files
      copy:
        src: ../app/
        dest: /home/ubuntu/simple-app/
        owner: ubuntu
        mode: '0755'

    - name: Install dependencies
      npm:
        path: /home/ubuntu/simple-app
      become_user: ubuntu

    - name: Start the app (background)
      shell: nohup npm start > output.log 2>&1 &
      args:
        chdir: /home/ubuntu/simple-app
      become_user: ubuntu
